name: 'Run Cypress tests'

on: [deployment_status]

jobs:
  cypress-chrome-test:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get pull request status
        id: pr_status
        run: |
          PULL_REQUEST_URL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].url')
          PULL_REQUEST_STATE=$(curl -s "$PULL_REQUEST_URL" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" | jq -r '.state')
          echo "::setOutput name=pr_state::$PULL_REQUEST_STATE"
      - name: Print curl output
        run: |
          DEPLOYMENT_URL=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls" | jq -r '.[0].url')
          curl -s "$DEPLOYMENT_URL" | jq
      - name: Exit if deployment failed
        if: ${{ steps.deployment_status_check.outputs.pr_state != 'open' }}
        run: |
          echo "Deployment failed!"
          echo ${{ steps.pr_status.outputs.pr_state }}
          exit 1

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env: 
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RETRIES: 1
          CYPRESS_RECORD_KEY: "null"
        with:
          install: true
          record: false
          browser: chrome
          config-file: cypress.config.js

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          retention-days: 3
          path: |
            cypress/videos
      - name: Post to a Slack channel
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04S0D9UQTH'
          payload: |
            {
              "text": "Cypress tests run successfully on chrome :white_check_mark:"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post to a Slack channel
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04S0D9UQTH'
          payload: |
            {
              "text": "Cypress tests are getting failed on chrome :x: here is the artifact: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    
  # cypress-firefox-test:
  #   if: github.event.deployment_status.state == 'success'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Run Cypress
  #       uses: cypress-io/github-action@v5
  #       env: 
  #         CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
  #         CYPRESS_RETRIES: 1
  #         install: true
  #       with:
  #         install: true
  #         record: false
  #         browser: firefox
  #         config-file: cypress.config.js


  #     - uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: cypress-videos
  #         retention-days: 3
  #         path: |
  #           cypress/videos
  #     - name: Post to a Slack channel
  #       if: success()
  #       uses: slackapi/slack-github-action@v1.23.0
  #       with:
  #         channel-id: 'C04S0D9UQTH'
  #         payload: |
  #           {
  #             "text": "Cypress tests run successfully on firefox :white_check_mark:"
  #           }
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  #     - name: Post to a Slack channel
  #       if: failure()
  #       uses: slackapi/slack-github-action@v1.23.0
  #       with:
  #         channel-id: 'C04S0D9UQTH'
  #         payload: |
  #           {
  #             "text": "Cypress tests are getting failed on firefox :x: here is the artifact: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  #           }
  #       env:
  #         SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


