name: 'Run Cypress tests'

on: [deployment_status]

jobs:
  cypress:
    # if my current deployment status is success and this is on PR open state then only run
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"
      - name: Load environment variables
        run: |
          export $(grep -v '^#' .env.cypress | xargs)
        env:
          ENV_FILE: .env.cypress
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          DEBUG: '@cypress/github-action'
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RETRIES: 1
        with:
          start: yarn cypress:run
          install-command: yarn install
          config-file: cypress.config.js
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          retention-days: 3
          path: |
            cypress/videos
      - name: Post to a Slack channel
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04S0D9UQTH'
          payload: |
            {
              "text": "Cypress tests run successfully :white_check_mark:"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post to a Slack channel
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04S0D9UQTH'
          payload: |
            {
              "text": "Cypress tests are getting failed :x: here is the artifact: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

