name: 'Run Cypress tests'
on: [deployment_status]
jobs:
  cypress:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          DEBUG: '@cypress/github-action'
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RETRIES: 1
        with:
          install-command: yarn install
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          retention-days: 3
          path: |
            cypress/videos
      - name: Send Slack message
        uses: rtCamp/action-slack-notify@v2.2.0
        if: always()
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          channel: '#cypresstest'
          message: |
            :heavy_check_mark: Cypress tests passed for ${{ github.repository }}!
            Check out the report here: ${{ steps.cypress.outputs }}

