name: 'Run Cypress tests'

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - "main"

jobs:
  cypress:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        env:
          DEBUG: '@cypress/github-action'
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RETRIES: 1
        with:
          install-command: yarn install
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          retention-days: 3
          path: |
            cypress/videos
      - name: Post to a Slack channel
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C02B1AD98P2'
          payload: |
            {
              "text": "Cypress tests runs successfully :white_check_mark:"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Post to a Slack channel
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C02B1AD98P2'
          payload: |
            {
              "text": "Cypress tests are getting failed :x: here is the artifact: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

